// AUTO-GENERATED from tokens.css by export.mjs. VE contract bound to the brand --bnd-* layer.
import { createGlobalThemeContract } from "@vanilla-extract/css";

export const vars = createGlobalThemeContract(
  {
    colorForest: "color-forest",
    colorForestDeep: "color-forest-deep",
    colorPaper: "color-paper",
    colorCard: "color-card",
    colorCardAlt: "color-card-alt",
    colorInk: "color-ink",
    colorInkSoft: "color-ink-soft",
    colorInkMono: "color-ink-mono",
    colorLine: "color-line",
    colorWhite: "color-white",
    colorForestTint: "color-forest-tint",
    colorForestSoft: "color-forest-soft",
    colorOnForest: "color-on-forest",
    colorOnForestSoft: "color-on-forest-soft",
    colorOnForestLine: "color-on-forest-line",
    colorClay: "color-clay",
    colorClayTint: "color-clay-tint",
    colorAmber: "color-amber",
    colorAmberTint: "color-amber-tint",
    fontDisplay: "font-display",
    fontMono: "font-mono",
    textMicro: "text-micro",
    textLabel: "text-label",
    textCaption: "text-caption",
    textSmall: "text-small",
    textMeta: "text-meta",
    textBody: "text-body",
    textLead: "text-lead",
    textTitle: "text-title",
    textH3: "text-h3",
    textH2: "text-h2",
    textH1: "text-h1",
    textDisplay: "text-display",
    sizeReadable: "size-readable",
    sizeProse: "size-prose",
    sizeCard: "size-card",
    sizeCardSm: "size-card-sm",
    sizeContainer: "size-container",
    sizeWide: "size-wide",
    radiusSm: "radius-sm",
    radiusMd: "radius-md",
    radiusLg: "radius-lg",
    radiusPill: "radius-pill",
    space0: "space-0",
    spacePx: "space-px",
    space1: "space-1",
    space2: "space-2",
    space3: "space-3",
    space4: "space-4",
    space5: "space-5",
    space6: "space-6",
    space7: "space-7",
    space8: "space-8",
    space10: "space-10",
    space12: "space-12",
    space16: "space-16",
    space20: "space-20",
    space24: "space-24",
    controlMinTapTarget: "control-min-tap-target",
    controlSm: "control-sm",
    controlMd: "control-md",
    controlLg: "control-lg",
    gradeEnforced: "grade-enforced",
    gradeEnforcedBg: "grade-enforced-bg",
    gradeEnforcedFg: "grade-enforced-fg",
    gradeEnforcedOnDark: "grade-enforced-on-dark",
    gradeEnforcedOnDarkBg: "grade-enforced-on-dark-bg",
    gradePartial: "grade-partial",
    gradePartialBg: "grade-partial-bg",
    gradePartialFg: "grade-partial-fg",
    gradePartialOnDark: "grade-partial-on-dark",
    gradePartialOnDarkBg: "grade-partial-on-dark-bg",
    gradeAspirational: "grade-aspirational",
    gradeAspirationalBg: "grade-aspirational-bg",
    gradeAspirationalFg: "grade-aspirational-fg",
    gradeAspirationalOnDark: "grade-aspirational-on-dark",
    gradeAspirationalOnDarkBg: "grade-aspirational-on-dark-bg",
  },
  (_value, path) => `--bnd-${path}`,
);
