// AUTO-GENERATED from tokens.css by export.mjs. VE contract bound to the brand --bs-* layer.
import { createGlobalThemeContract } from "@vanilla-extract/css";

export const vars = createGlobalThemeContract(
  {
    colorForest: "color-forest",
    colorForestDeep: "color-forest-deep",
    colorPaper: "color-paper",
    colorCard: "color-card",
    colorCardAlt: "color-card-alt",
    colorInk: "color-ink",
    colorInkSoft: "color-ink-soft",
    colorInkMono: "color-ink-mono",
    colorLine: "color-line",
    colorWhite: "color-white",
    colorForestTint: "color-forest-tint",
    colorForestSoft: "color-forest-soft",
    colorClay: "color-clay",
    colorClayTint: "color-clay-tint",
    colorAmber: "color-amber",
    colorAmberTint: "color-amber-tint",
    fontDisplay: "font-display",
    fontMono: "font-mono",
    textH1: "text-h1",
    textH2: "text-h2",
    textTitle: "text-title",
    textBody: "text-body",
    textLabel: "text-label",
    radiusLg: "radius-lg",
    radiusMd: "radius-md",
    gradeEnforced: "grade-enforced",
    gradeEnforcedBg: "grade-enforced-bg",
    gradeEnforcedFg: "grade-enforced-fg",
    gradeEnforcedOnDark: "grade-enforced-on-dark",
    gradeEnforcedOnDarkBg: "grade-enforced-on-dark-bg",
    gradePartial: "grade-partial",
    gradePartialBg: "grade-partial-bg",
    gradePartialFg: "grade-partial-fg",
    gradePartialOnDark: "grade-partial-on-dark",
    gradePartialOnDarkBg: "grade-partial-on-dark-bg",
    gradeAspirational: "grade-aspirational",
    gradeAspirationalBg: "grade-aspirational-bg",
    gradeAspirationalFg: "grade-aspirational-fg",
    gradeAspirationalOnDark: "grade-aspirational-on-dark",
    gradeAspirationalOnDarkBg: "grade-aspirational-on-dark-bg",
  },
  (_value, path) => `--bs-${path}`,
);
