// AUTO-GENERATED from tokens.css by export.mjs. StyleX vars bound to the brand --bs-* layer.
import * as stylex from "@stylexjs/stylex";

export const tokens = stylex.defineVars({
  colorForest: "var(--bs-color-forest)",
  colorForestDeep: "var(--bs-color-forest-deep)",
  colorPaper: "var(--bs-color-paper)",
  colorCard: "var(--bs-color-card)",
  colorCardAlt: "var(--bs-color-card-alt)",
  colorInk: "var(--bs-color-ink)",
  colorInkSoft: "var(--bs-color-ink-soft)",
  colorInkMono: "var(--bs-color-ink-mono)",
  colorLine: "var(--bs-color-line)",
  colorWhite: "var(--bs-color-white)",
  colorForestTint: "var(--bs-color-forest-tint)",
  colorForestSoft: "var(--bs-color-forest-soft)",
  colorClay: "var(--bs-color-clay)",
  colorClayTint: "var(--bs-color-clay-tint)",
  colorAmber: "var(--bs-color-amber)",
  colorAmberTint: "var(--bs-color-amber-tint)",
  fontDisplay: "var(--bs-font-display)",
  fontMono: "var(--bs-font-mono)",
  textH1: "var(--bs-text-h1)",
  textH2: "var(--bs-text-h2)",
  textTitle: "var(--bs-text-title)",
  textBody: "var(--bs-text-body)",
  textLabel: "var(--bs-text-label)",
  radiusLg: "var(--bs-radius-lg)",
  radiusMd: "var(--bs-radius-md)",
  gradeEnforced: "var(--bs-grade-enforced)",
  gradeEnforcedBg: "var(--bs-grade-enforced-bg)",
  gradeEnforcedFg: "var(--bs-grade-enforced-fg)",
  gradeEnforcedOnDark: "var(--bs-grade-enforced-on-dark)",
  gradeEnforcedOnDarkBg: "var(--bs-grade-enforced-on-dark-bg)",
  gradePartial: "var(--bs-grade-partial)",
  gradePartialBg: "var(--bs-grade-partial-bg)",
  gradePartialFg: "var(--bs-grade-partial-fg)",
  gradePartialOnDark: "var(--bs-grade-partial-on-dark)",
  gradePartialOnDarkBg: "var(--bs-grade-partial-on-dark-bg)",
  gradeAspirational: "var(--bs-grade-aspirational)",
  gradeAspirationalBg: "var(--bs-grade-aspirational-bg)",
  gradeAspirationalFg: "var(--bs-grade-aspirational-fg)",
  gradeAspirationalOnDark: "var(--bs-grade-aspirational-on-dark)",
  gradeAspirationalOnDarkBg: "var(--bs-grade-aspirational-on-dark-bg)",
});
